
// import fonts from "../utils/fonts";
import HomePage from "../components/templates/HomePage";
import Layout from "../layouts/Layout";
import "./globals.css";

export const metadata = {
  title: "camping web",
  description: "Generated by create next app",
  icons: { icon: "globe.svg" },
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-Dana font-normal">
        <Layout>
         {children}
        </Layout>
      </body>
    </html>
  );
}
